
 export const ALL_CHARACTER_REQUEST = 'ALL_CHARACTER_REQUEST';
 export const ALL_CHARACTER_SUCCESS = 'ALL_CHARACTER_SUCCESS';
 export const ALL_SEARCHED_CHARACTER_SUCCESS = 'ALL_SEARCHED_CHARACTER_SUCCESS';
 export const ALL_CHARACTER_FAIL = 'ALL_CHARACTER_FAIL';
