
 export const ALL_CHARACTER_REQUEST:string = 'ALL_CHARACTER_REQUEST';
 export const ALL_CHARACTER_SUCCESS:string = 'ALL_CHARACTER_SUCCESS';
 export const ALL_CHARACTER_FAIL:string = 'ALL_CHARACTER_FAIL';
 export const ALL_FAVORITE_LIST:string = 'ALL_FAVORITE_LIST';
